// AirRO web-client build.
//
// The app has NO modules: every .js/.jsx file runs as a classic <script> and they share a single
// global/lexical scope (e.g. icons.jsx does `const IconRefresh = ...` and distribution.jsx uses
// `<IconRefresh/>` bare). React comes from a CDN UMD global. Script ORDER matters.
//
// So we DO NOT bundle (esbuild's bundler would wrap each file in its own module scope and break the
// bare cross-file references) and we DO NOT rename identifiers. We simply transform each file's JSX
// away with esbuild (loader jsx, classic React.createElement, target es2018) and CONCATENATE the
// outputs in the exact HTML load order into one dist/app.js — identical semantics to loading the 26
// separate scripts, minus the in-browser Babel compile.
//
// Sourcemap: an "indexed" source map (sections[]) — each file's own esbuild map is placed at its line
// offset in the combined file, so DevTools shows every original file with correct line numbers.
//
// Usage:  node build.mjs            (safe minify: whitespace + syntax, identifiers preserved)
//         node build.mjs --no-minify

import { transform } from 'esbuild';
import { readFile, writeFile, mkdir, readdir, unlink } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { createHash } from 'node:crypto';
import { execSync } from 'node:child_process';

const ROOT = dirname(fileURLToPath(import.meta.url));
const MINIFY = !process.argv.includes('--no-minify');

// Build stamp for "which build is live" (shown in the app footer + /api/v1/version). The COMMIT and
// BUILD TIME are display-only and are embedded AFTER the content hash below, so they never enter the
// freshness hash — an identical-source rebuild keeps the same `version` and never false-triggers the
// "new version" banner, while ops can still see the exact commit + clock the bundle was built from.
const gitCommit = (() => {
  if (process.env.GIT_COMMIT) return process.env.GIT_COMMIT.slice(0, 12);
  try { return execSync('git rev-parse --short=12 HEAD', { cwd: ROOT, stdio: ['ignore', 'pipe', 'ignore'] }).toString().trim(); }
  catch { return 'nogit'; }
})();
const builtAt = new Date().toISOString();

// EXACT script load order from index.html (the <script src> sequence).
// Keep this in sync with the HTML if scripts are ever added/reordered.
const FILES = [
  'finance-i18n.js',
  'finance-period.js',
  'data.js',
  'finance-store.js',
  'finance-hrd.js',
  'company-store.js',
  'app-config.js',
  'api.js',
  'cloud.js',
  'icons.jsx',
  'charts.jsx',
  'ui-dropdown.jsx',
  'finance-datepicker.jsx',
  'finance-app.jsx',
  'finance-auth.jsx',
  'finance-alerts.jsx',
  'finance-backup.js',
  'finance-settings.jsx',
  'finance-edit.jsx',
  'finance-reports.jsx',
  'finance-hrd.jsx',
  'company.jsx',
  'finance-setoran.jsx',
  'finance-users.jsx',
  'distribution.jsx',
  'gudang.jsx',
  'finance-shell.jsx',
];

const countNL = (s) => { let n = 0; for (let i = 0; i < s.length; i++) if (s.charCodeAt(i) === 10) n++; return n; };

async function build() {
  const t0 = Date.now();

  // Pre-read every source so we can derive a CONTENT build stamp before writing the
  // bundle. The stamp is a short sha256 of the (filename + content) of all sources: it
  // changes iff the code changes and is otherwise deterministic (so an identical rebuild
  // produces the identical stamp — no false "new version" prompts). The app embeds this
  // as window.__AIRRO_BUILD__ and the server serves it from version.json; the client
  // compares the two to show the "new version available" banner. See finance-shell.jsx.
  const srcs = [];
  for (const file of FILES) srcs.push({ file, src: await readFile(join(ROOT, file), 'utf8') });
  const version = createHash('sha256').update(srcs.map((s) => s.file + '\0' + s.src).join('\0')).digest('hex').slice(0, 12);

  let out = `// GENERATED by build.mjs — do not edit. Source: the individual .js/.jsx files.\n`;
  out += `window.__AIRRO_BUILD__=${JSON.stringify(version)};\n`;   // freshness hash (source-only, deterministic)
  out += `window.__AIRRO_COMMIT__=${JSON.stringify(gitCommit)};window.__AIRRO_BUILT_AT__=${JSON.stringify(builtAt)};\n`;   // display stamp
  let genLine = countNL(out);   // counts ALL preamble lines above, so the source map stays aligned
  const sections = [];

  for (const { file, src } of srcs) {
    const loader = file.endsWith('.jsx') ? 'jsx' : 'js';
    const res = await transform(src, {
      loader,
      target: 'es2018',
      format: undefined,          // NOT esm/cjs — plain script text, global scope preserved
      sourcemap: true,
      sourcefile: file,
      sourcesContent: true,
      legalComments: 'none',
      // Safe minify only: shrink whitespace + fold syntax, but NEVER rename identifiers
      // (top-level names are shared across files by bare reference).
      minify: false,
      minifyWhitespace: MINIFY,
      minifySyntax: MINIFY,
      minifyIdentifiers: false,
    });

    const banner = `//#region ${file}\n`;
    out += banner;
    genLine += countNL(banner);

    let code = res.code;
    if (!code.endsWith('\n')) code += '\n';
    sections.push({ offset: { line: genLine, column: 0 }, map: JSON.parse(res.map) });
    out += code;
    genLine += countNL(code);

    const end = `//#endregion ${file}\n`;
    out += end;
    genLine += countNL(end);
  }

  const bundleName = `app.${version}.js`;                 // CONTENT-HASHED filename → the cache-bust
  const mapJson = JSON.stringify({ version: 3, sections });
  const distDir = join(ROOT, 'dist');
  await mkdir(distDir, { recursive: true });

  // Remove stale hashed bundles so dist/ doesn't grow unbounded across deploys (app.js is overwritten).
  for (const f of await readdir(distDir)) {
    if (/^app\.[0-9a-f]+\.js(\.map)?$/.test(f)) await unlink(join(distDir, f)).catch(() => {});
  }
  // PRIMARY: the hashed bundle index.html points at. Its URL changes every deploy, so a reload of the
  // (no-store) index.html always fetches the matching bundle and can never reuse a stale cached one.
  await writeFile(join(distDir, bundleName), out + `//# sourceMappingURL=${bundleName}.map\n`, 'utf8');
  await writeFile(join(distDir, bundleName + '.map'), mapJson, 'utf8');
  // TRANSITION FALLBACK at the old stable path, for any index.html a browser cached before this change
  // (served no-cache so it's never stale). Safe to drop after one release.
  await writeFile(join(distDir, 'app.js'), out + '//# sourceMappingURL=app.js.map\n', 'utf8');
  await writeFile(join(distDir, 'app.js.map'), mapJson, 'utf8');
  // Build stamp the server serves at GET /api/v1/version + the client freshness check. SAME `version`.
  await writeFile(join(ROOT, 'version.json'), JSON.stringify({ version, commit: gitCommit, builtAt }) + '\n', 'utf8');

  // SERVED index.html (dist/index.html) generated from the source, pointing the app <script> at the
  // hashed bundle. The source index.html is NEVER modified (no git churn); nginx serves dist/index.html.
  const srcHtml = await readFile(join(ROOT, 'index.html'), 'utf8');
  const builtHtml = srcHtml.replace(/\/dist\/app(?:\.[0-9a-f]+)?\.js(?:\?v=[^"']*)?/g, `/dist/${bundleName}`);
  if (!builtHtml.includes(`/dist/${bundleName}`)) throw new Error('build: could not rewrite the /dist/app.js <script src> in index.html');
  await writeFile(join(distDir, 'index.html'), builtHtml, 'utf8');

  // ASSERTION — single source of truth. The hash EMBEDDED in the bundle, written to version.json, and
  // REFERENCED by index.html must all equal `version`. Any drift makes the "new version" banner loop,
  // so fail the build loudly rather than ship it.
  const embedded = (out.match(/window\.__AIRRO_BUILD__="([0-9a-f]+)"/) || [])[1];
  const fromJson = JSON.parse(await readFile(join(ROOT, 'version.json'), 'utf8')).version;
  if (embedded !== version || fromJson !== version || !builtHtml.includes(bundleName)) {
    throw new Error(`build: version SOT mismatch — embedded=${embedded} version.json=${fromJson} indexRefsHashed=${builtHtml.includes(bundleName)} expected=${version}`);
  }

  const bytes = Buffer.byteLength(out, 'utf8');
  console.log(`built dist/${bundleName} + dist/index.html  (${FILES.length} files, ${(bytes / 1024).toFixed(0)} KB${MINIFY ? ', minified' : ', unminified'}, build ${version}) in ${Date.now() - t0}ms`);
}

build().catch((e) => { console.error('BUILD FAILED:', e); process.exit(1); });
