// AirRO web-client build.
//
// The app has NO modules: every .js/.jsx file runs as a classic <script> and they share a single
// global/lexical scope (e.g. icons.jsx does `const IconRefresh = ...` and distribution.jsx uses
// `<IconRefresh/>` bare). React comes from a CDN UMD global. Script ORDER matters.
//
// So we DO NOT bundle (esbuild's bundler would wrap each file in its own module scope and break the
// bare cross-file references) and we DO NOT rename identifiers. We simply transform each file's JSX
// away with esbuild (loader jsx, classic React.createElement, target es2018) and CONCATENATE the
// outputs in the exact HTML load order into one dist/app.js — identical semantics to loading the 26
// separate scripts, minus the in-browser Babel compile.
//
// Sourcemap: an "indexed" source map (sections[]) — each file's own esbuild map is placed at its line
// offset in the combined file, so DevTools shows every original file with correct line numbers.
//
// Usage:  node build.mjs            (safe minify: whitespace + syntax, identifiers preserved)
//         node build.mjs --no-minify

import { transform } from 'esbuild';
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const ROOT = dirname(fileURLToPath(import.meta.url));
const MINIFY = !process.argv.includes('--no-minify');

// EXACT script load order from "AirRO Water - Daily Finance Manager.html" (the <script src> sequence).
// Keep this in sync with the HTML if scripts are ever added/reordered.
const FILES = [
  'finance-i18n.js',
  'finance-period.js',
  'data.js',
  'finance-store.js',
  'finance-hrd.js',
  'company-store.js',
  'app-config.js',
  'api.js',
  'cloud.js',
  'icons.jsx',
  'charts.jsx',
  'ui-dropdown.jsx',
  'finance-datepicker.jsx',
  'finance-app.jsx',
  'finance-auth.jsx',
  'finance-alerts.jsx',
  'finance-backup.js',
  'finance-settings.jsx',
  'finance-edit.jsx',
  'finance-reports.jsx',
  'finance-hrd.jsx',
  'company.jsx',
  'finance-setoran.jsx',
  'finance-users.jsx',
  'distribution.jsx',
  'gudang.jsx',
  'finance-shell.jsx',
];

const countNL = (s) => { let n = 0; for (let i = 0; i < s.length; i++) if (s.charCodeAt(i) === 10) n++; return n; };

async function build() {
  const t0 = Date.now();
  let out = `// GENERATED by build.mjs — do not edit. Source: the individual .js/.jsx files.\n`;
  let genLine = countNL(out);
  const sections = [];

  for (const file of FILES) {
    const src = await readFile(join(ROOT, file), 'utf8');
    const loader = file.endsWith('.jsx') ? 'jsx' : 'js';
    const res = await transform(src, {
      loader,
      target: 'es2018',
      format: undefined,          // NOT esm/cjs — plain script text, global scope preserved
      sourcemap: true,
      sourcefile: file,
      sourcesContent: true,
      legalComments: 'none',
      // Safe minify only: shrink whitespace + fold syntax, but NEVER rename identifiers
      // (top-level names are shared across files by bare reference).
      minify: false,
      minifyWhitespace: MINIFY,
      minifySyntax: MINIFY,
      minifyIdentifiers: false,
    });

    const banner = `//#region ${file}\n`;
    out += banner;
    genLine += countNL(banner);

    let code = res.code;
    if (!code.endsWith('\n')) code += '\n';
    sections.push({ offset: { line: genLine, column: 0 }, map: JSON.parse(res.map) });
    out += code;
    genLine += countNL(code);

    const end = `//#endregion ${file}\n`;
    out += end;
    genLine += countNL(end);
  }

  out += '//# sourceMappingURL=app.js.map\n';

  await mkdir(join(ROOT, 'dist'), { recursive: true });
  await writeFile(join(ROOT, 'dist', 'app.js'), out, 'utf8');
  await writeFile(join(ROOT, 'dist', 'app.js.map'), JSON.stringify({ version: 3, sections }), 'utf8');

  const bytes = Buffer.byteLength(out, 'utf8');
  console.log(`built dist/app.js  (${FILES.length} files, ${(bytes / 1024).toFixed(0)} KB${MINIFY ? ', minified w/s+syntax' : ', unminified'}) in ${Date.now() - t0}ms`);
}

build().catch((e) => { console.error('BUILD FAILED:', e); process.exit(1); });
